spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      #url: jdbc:mysql://192.168.99.100:3306/cz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      url: jdbc:mysql://10.11.4.87:3307/cz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456