version: '3'
services:
  config:
    build: ./config
    ports:
      - "8888:8888"
  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=cz
  registry:
    build: ./registry
    ports:
      - "8761:8761"
    depends_on:
      - config
    environment:
      - SPRING_PROFILES_ACTIVE=prd
  gateway:
    build: ./gateway
    depends_on:
      - config
    links:
      - registry
      - service-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prd
  service-1:
    build: ./service-1
    ports:
      - "8088:8088"
    depends_on:
      - config
    links:
      - registry
    # - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=prd


