version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cz
  config:
    build: ./config
    ports:
      - 8888:8888
  registry:
    build: ./registry
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=notebook
  gateway:
    build: ./gateway
    ports:
      - 8080:8080
    links:
      - registry
      - service-1
    environment:
      - SPRING_PROFILES_ACTIVE=notebook
  service-1:
    build: ./service-1
    ports:
      - 8088:8088
    links:
      - registry
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=notebook

