spring:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456